"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pypir.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/armaniakines/PycharmProjects/PyPIR/PyPIR_icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'wolframalpha',
        'wikipedia',
        'pyttsx3',
        'pyowm',
        'twilio',
        'googlemaps'])
